In [2]:
import numpy as np

def sigmoid(x):
    """Сигмоидальная функция активации."""
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    """Производная сигмоиды."""
    return sigmoid(x) * (1 - sigmoid(x))

def forward_pass(X, W1, b1, W2, b2):
    """Прямой проход через сеть."""
    Z1 = np.dot(X, W1.T) + b1
    H = sigmoid(Z1)

    Z2 = np.dot(H, W2.T) + b2
    Y = sigmoid(Z2)

    return Y, H, Z1

def loss(y_pred, y_true):
    """Функция потерь (MSE)."""
    return 0.5 * np.mean((y_pred - y_true)**2)

def loss_derivative(y_pred, y_true):
    """Производная функции потерь (MSE)."""
    return y_pred - y_true

def backward_pass(X, Y_pred, Y_true, H, Z1, W1, b1, W2, b2, lr):
    """Обратный проход и обновление весов."""
    # Производные
    d_L_d_Y = loss_derivative(Y_pred, Y_true)
    d_Y_d_Z2 = sigmoid_derivative(np.dot(H, W2.T))
    d_Z2_d_W2 = H
    d_Z2_d_b2 = 1
    d_Y_d_b2 = d_Y_d_Z2 * d_Z2_d_b2

    d_L_d_Z2 = d_L_d_Y * d_Y_d_Z2

    d_L_d_W2 = np.dot(d_L_d_Z2.T, d_Z2_d_W2)
    d_L_d_b2 = np.sum(d_L_d_Z2, axis=0)


    d_H_d_Z1 = sigmoid_derivative(Z1) # Исправлено
    d_Z1_d_W1 = X
    d_Z1_d_b1 = 1

    d_Z2_d_H = W2
    d_L_d_H = np.dot(d_L_d_Z2, d_Z2_d_H)

    d_L_d_Z1 = d_L_d_H * d_H_d_Z1

    d_L_d_W1 = np.dot(d_L_d_Z1.T, d_Z1_d_W1)
    d_L_d_b1 = np.sum(d_L_d_Z1, axis=0)

    # Обновление весов
    W1 -= lr * d_L_d_W1
    b1 -= lr * d_L_d_b1
    W2 -= lr * d_L_d_W2
    b2 -= lr * d_L_d_b2

    return W1, b1, W2, b2


def train(X, Y, lr = 0.01, epochs = 10000):
    """Обучение персептрона."""
    input_size = X.shape[1]
    hidden_size = 2
    output_size = 1

    # Инициализация весов случайными значениями
    W1 = np.random.randn(hidden_size, input_size)
    b1 = np.random.randn(hidden_size)
    W2 = np.random.randn(output_size, hidden_size)
    b2 = np.random.randn(output_size)


    loss_history = []

    for epoch in range(epochs):
        # Прямой проход
        Y_pred, H, Z1 = forward_pass(X, W1, b1, W2, b2)

        # Вычисление ошибки
        current_loss = loss(Y_pred, Y)
        loss_history.append(current_loss)

        # Обратный проход и обновление весов
        W1, b1, W2, b2 = backward_pass(X, Y_pred, Y, H, Z1, W1, b1, W2, b2, lr)

        if epoch % (epochs/10) == 0:
            print(f"Эпоха {epoch}/{epochs}, Ошибка: {current_loss:.4f}")

    return W1, b1, W2, b2, loss_history


if __name__ == "__main__":
    # Данные
    X = np.array([
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 1]
    ])

    Y = np.array([
       [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [0]
    ])
    # Обучение
    W1_trained, b1_trained, W2_trained, b2_trained, loss_history = train(X, Y, lr=0.1, epochs=10000)

    print("\nОбучение завершено!")
    print("Веса первого слоя:\n", W1_trained)
    print("Смещения первого слоя:\n", b1_trained)
    print("Веса второго слоя:\n", W2_trained)
    print("Смещения второго слоя:\n", b2_trained)

    # Тестирование
    Y_pred, _, _ = forward_pass(X, W1_trained, b1_trained, W2_trained, b2_trained)
    print("\nПрогнозы:")
    for i in range(len(Y)):
        print(f"Вход: {X[i]}, Выход: {Y_pred[i][0]:.4f}, Ожидаемый выход: {Y[i][0]}")

Эпоха 0/10000, Ошибка: 0.1260
Эпоха 1000/10000, Ошибка: 0.0848
Эпоха 2000/10000, Ошибка: 0.0473
Эпоха 3000/10000, Ошибка: 0.0397
Эпоха 4000/10000, Ошибка: 0.0369
Эпоха 5000/10000, Ошибка: 0.0354
Эпоха 6000/10000, Ошибка: 0.0345
Эпоха 7000/10000, Ошибка: 0.0339
Эпоха 8000/10000, Ошибка: 0.0335
Эпоха 9000/10000, Ошибка: 0.0332

Обучение завершено!
Веса первого слоя:
 [[-3.28205576 -4.70142247 -4.70142157]
 [ 6.54479488 -5.56905648 -5.56905158]]
Смещения первого слоя:
 [ 4.5705882  -1.17951146]
Веса второго слоя:
 [[-6.02124468  8.06175343]]
Смещения второго слоя:
 [-0.01390131]

Прогнозы:
Вход: [0 0 0], Выход: 0.0167, Ожидаемый выход: 0
Вход: [0 0 1], Выход: 0.0563, Ожидаемый выход: 0
Вход: [0 1 0], Выход: 0.0563, Ожидаемый выход: 0
Вход: [0 1 1], Выход: 0.4846, Ожидаемый выход: 1
Вход: [1 0 0], Выход: 0.9641, Ожидаемый выход: 1
Вход: [1 0 1], Выход: 0.9682, Ожидаемый выход: 1
Вход: [1 1 0], Выход: 0.9682, Ожидаемый выход: 1
Вход: [1 1 1], Выход: 0.5023, Ожидаемый выход: 0


#Без смещений


In [3]:
import numpy as np

def sigmoid(x):
    """Сигмоидальная функция активации."""
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    """Производная сигмоиды."""
    return sigmoid(x) * (1 - sigmoid(x))

def forward_pass(X, W1, W2):
    """Прямой проход через сеть без смещений."""
    Z1 = np.dot(X, W1.T)
    H = sigmoid(Z1)

    Z2 = np.dot(H, W2.T)
    Y = sigmoid(Z2)

    return Y, H, Z1

def loss(y_pred, y_true):
    """Функция потерь (MSE)."""
    return 0.5 * np.mean((y_pred - y_true)**2)

def loss_derivative(y_pred, y_true):
    """Производная функции потерь (MSE)."""
    return y_pred - y_true

def backward_pass(X, Y_pred, Y_true, H, Z1, W1, W2, lr):
    """Обратный проход и обновление весов без смещений."""
    # Производные
    d_L_d_Y = loss_derivative(Y_pred, Y_true)
    d_Y_d_Z2 = sigmoid_derivative(np.dot(H, W2.T))
    d_Z2_d_W2 = H

    d_L_d_Z2 = d_L_d_Y * d_Y_d_Z2
    d_L_d_W2 = np.dot(d_L_d_Z2.T, d_Z2_d_W2)


    d_H_d_Z1 = sigmoid_derivative(Z1) # Исправлено
    d_Z1_d_W1 = X

    d_Z2_d_H = W2
    d_L_d_H = np.dot(d_L_d_Z2, d_Z2_d_H)
    d_L_d_Z1 = d_L_d_H * d_H_d_Z1
    d_L_d_W1 = np.dot(d_L_d_Z1.T, d_Z1_d_W1)


    # Обновление весов (без смещений)
    W1 -= lr * d_L_d_W1
    W2 -= lr * d_L_d_W2

    return W1, W2


def train(X, Y, lr = 0.01, epochs = 10000):
    """Обучение персептрона без смещений."""
    input_size = X.shape[1]
    hidden_size = 2
    output_size = 1

    # Инициализация весов случайными значениями
    W1 = np.random.randn(hidden_size, input_size)
    W2 = np.random.randn(output_size, hidden_size)


    loss_history = []

    for epoch in range(epochs):
        # Прямой проход
        Y_pred, H, Z1 = forward_pass(X, W1, W2)

        # Вычисление ошибки
        current_loss = loss(Y_pred, Y)
        loss_history.append(current_loss)

        # Обратный проход и обновление весов
        W1, W2 = backward_pass(X, Y_pred, Y, H, Z1, W1, W2, lr)

        if epoch % (epochs/10) == 0:
            print(f"Эпоха {epoch}/{epochs}, Ошибка: {current_loss:.4f}")

    return W1, W2, loss_history


if __name__ == "__main__":
    # Данные
    X = np.array([
        [0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 1]
    ])

    Y = np.array([
       [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [0]
    ])
    # Обучение
    W1_trained, W2_trained, loss_history = train(X, Y, lr=0.1, epochs=10000)

    print("\nОбучение завершено!")
    print("Веса первого слоя:\n", W1_trained)
    print("Веса второго слоя:\n", W2_trained)


    # Тестирование
    Y_pred, _, _ = forward_pass(X, W1_trained, W2_trained)
    print("\nПрогнозы:")
    for i in range(len(Y)):
        print(f"Вход: {X[i]}, Выход: {Y_pred[i][0]:.4f}, Ожидаемый выход: {Y[i][0]}")

Эпоха 0/10000, Ошибка: 0.1406
Эпоха 1000/10000, Ошибка: 0.0758
Эпоха 2000/10000, Ошибка: 0.0687
Эпоха 3000/10000, Ошибка: 0.0653
Эпоха 4000/10000, Ошибка: 0.0629
Эпоха 5000/10000, Ошибка: 0.0611
Эпоха 6000/10000, Ошибка: 0.0599
Эпоха 7000/10000, Ошибка: 0.0590
Эпоха 8000/10000, Ошибка: 0.0583
Эпоха 9000/10000, Ошибка: 0.0578

Обучение завершено!
Веса первого слоя:
 [[ 4.86841272 -1.67034827  5.22529962]
 [-5.99591281 -1.86900754 -1.0686304 ]]
Веса второго слоя:
 [[  1.572141   -13.40212512]]

Прогнозы:
Вход: [0 0 0], Выход: 0.0027, Ожидаемый выход: 0
Вход: [0 0 1], Выход: 0.1344, Ожидаемый выход: 0
Вход: [0 1 0], Выход: 0.1762, Ожидаемый выход: 0
Вход: [0 1 1], Выход: 0.7014, Ожидаемый выход: 1
Вход: [1 0 0], Выход: 0.8215, Ожидаемый выход: 1
Вход: [1 0 1], Выход: 0.8264, Ожидаемый выход: 1
Вход: [1 1 0], Выход: 0.8184, Ожидаемый выход: 1
Вход: [1 1 1], Выход: 0.8278, Ожидаемый выход: 0


#Со встроенными библотеками

In [25]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import mean_squared_error
# Входные данные и целевые значения
inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])
targets = np.array([0, 0, 0, 1, 1, 1, 1, 0])

# Создание и обучение многослойного персептрона (MLP)
mlp = MLPClassifier(hidden_layer_sizes=(2,), 
                    activation='identity', #logistic-сишмоида, identity - без изменений
                    solver='sgd', 
                    learning_rate_init=0.5, 
                    max_iter=100000, 
                    random_state=42,
                    shuffle=False, # Отключаем перемешивание
                    )
mlp.fit(inputs, targets)

# Извлечение весов
weights_hidden = mlp.coefs_[0]
weights_output = mlp.coefs_[1]
#смещения
biases_hidden = mlp.intercepts_[0]
biases_output = mlp.intercepts_[1]
# Вывод обученных весов
print("Обученные веса скрытого слоя:")
print(weights_hidden)
print("\nОбученные веса выходного слоя:")
print(weights_output)
print("\nОбученные смещения скрытого слоя:")
print(biases_hidden)
print("\nОбученные смещения выходного слоя:")
print(biases_output)

# Проверка персептрона
print("\nПроверка персептрона:")
predictions = mlp.predict(inputs)
for i in range(len(inputs)):
    print(f"Input: {inputs[i]}, Predicted: {predictions[i]}, Target: {targets[i]}")
mse = mean_squared_error(targets, predictions)
print(f"\nСреднеквадратичная ошибка (MSE): {mse}")
#сомнительный код

Обученные веса скрытого слоя:
[[-0.03267398  2.13886257]
 [ 0.61693506  0.23828005]
 [-0.53852984 -0.27396641]]

Обученные веса выходного слоя:
[[-0.47971112]
 [ 1.01512545]]

Обученные смещения скрытого слоя:
[-0.41154359  0.20911454]

Обученные смещения выходного слоя:
[-1.46175893]

Проверка персептрона:
Input: [0 0 0], Predicted: 0, Target: 0
Input: [0 0 1], Predicted: 0, Target: 0
Input: [0 1 0], Predicted: 0, Target: 0
Input: [0 1 1], Predicted: 0, Target: 1
Input: [1 0 0], Predicted: 1, Target: 1
Input: [1 0 1], Predicted: 1, Target: 1
Input: [1 1 0], Predicted: 1, Target: 1
Input: [1 1 1], Predicted: 1, Target: 0

Среднеквадратичная ошибка (MSE): 0.25


In [26]:
import numpy as np
import tensorflow as tf

# Входные данные и целевые значения
inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])
targets = np.array([0, 0, 0, 1, 1, 1, 1, 0])

# Преобразование данных в тензоры
inputs_tensor = tf.convert_to_tensor(inputs, dtype=tf.float32)
targets_tensor = tf.convert_to_tensor(targets, dtype=tf.int32)


# Создание модели
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, activation='sigmoid', use_bias=True, input_shape=(3,)), # Без смещений
    tf.keras.layers.Dense(1, activation='sigmoid', use_bias=True) # Без смещений
])


# Компиляция модели
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=['accuracy'])

# Обучение модели
model.fit(inputs_tensor, targets_tensor, epochs=100, verbose=1)


# Вывод весов
weights_hidden = model.layers[0].get_weights()[0]
# biases_hidden = np.zeros(shape=(2,)) # Смещения для скрытого слоя
weights_output = model.layers[1].get_weights()[0]
# biases_output = np.zeros(shape=(1,)) # Смещения для выходного слоя


print("Обученные веса скрытого слоя:")
print(weights_hidden)
print("\nОбученные смещения скрытого слоя (установлены в 0):")
print(biases_hidden)
print("\nОбученные веса выходного слоя:")
print(weights_output)
print("\nОбученные смещения выходного слоя (установлены в 0):")
print(biases_output)


# Проверка персептрона
predictions = model.predict(inputs_tensor).round()
print("\nПроверка персептрона:")
for i in range(len(inputs)):
        print(f"Input: {inputs[i]}, Predicted: {(predictions[i][0])}, Target: {targets[i]}")

C:\Users\Владимир\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 791ms/step - accuracy: 0.3750 - loss: 0.7142
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.3750 - loss: 0.7141
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3750 - loss: 0.7139
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.3750 - loss: 0.7138
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.3750 - loss: 0.7136
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.3750 - loss: 0.7135
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.3750 - loss: 0.7133
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7132
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.7130
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5000 - loss: 0.7129
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.7127
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - l

#В классе

In [28]:
import numpy as np

class NeuronMath:
    def __init__(self, weights):
        self.weights = weights
        self.x = None  # Входные данные
        self.y = None  # Выход

    def activate(self, inputs):
        self.x = inputs
        weighted_sum = np.dot(inputs, self.weights[:-1])  # Crucial!
        weighted_sum += self.weights[-1]
        self.y = 1 if weighted_sum >= 0 else 0
        return self.y

    @staticmethod
    def next_value(val, min_val, max_val, step):
        for i in range(len(val) - 1, -1, -1):
            if val[i] < max_val[i]:
                val[i] += step[i]
                for j in range(i + 1, len(val)):
                    val[j] = min_val[j]
                return True
        return False

    @staticmethod
    def compare_arrays(arr1, arr2):
        for i in range(min(len(arr1), len(arr2))):
            if arr1[i] < arr2[i]:
                return -1
            elif arr1[i] > arr2[i]:
                return 1
        if len(arr1) < len(arr2):
            return -1
        elif len(arr1) > len(arr2):
            return 1
        return 0
def bin_func3_neuron_test():
    x = np.array([
        [0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1],
        [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]
    ], dtype=float)
    
    d = np.array([0, 0, 0, 1, 1, 1, 1, 0], dtype=float)
    min_val = np.array([-1, -1, -1, -1.5, -1, -1, -1, -1.5, 0, 0, 0, 0, -1, -1, 0, -2.5], dtype=float)
    max_val = np.array([1, 1, 1, 1.5, 1, 1, 1, 1.5, 0, 0, 0, 0, 1, 1, 0, 2.5], dtype=float)
    val = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=float)
    step = np.array([.5, .5, .5, .5, .5, .5, .5, .5, .5, .5, .5, .5, .5, .5, .5, .5], dtype=float)
    
    n1 = NeuronMath(np.zeros(4, dtype=float))
    n2 = NeuronMath(np.zeros(4, dtype=float))
    n3 = NeuronMath(np.zeros(4, dtype=float))
    n4 = NeuronMath(np.zeros(4, dtype=float))
    
    print("d:", ", ".join(str(int(i)) for i in d) + ";")
    
    count = 0
    while NeuronMath.next_value(val, min_val, max_val, step):
        n1.weights = val[0:4].copy()
        n2.weights = val[4:8].copy()
        n3.weights = val[8:12].copy()
        n4.weights = val[12:16].copy()
        
        y = np.zeros(8, dtype=float)
        for i in range(len(x)):
            y[i] = n4.activate([n1.activate(x[i]), n2.activate(x[i]), n3.activate(x[i])])
    
        if NeuronMath.compare_arrays(y, d) == 0:
            print("w1:", ", ".join(str(v) for v in n1.weights), ";    ", end="")
            print("w2:", ", ".join(str(v) for v in n2.weights), ";    ", end="")
            print("w3:", ", ".join(str(v) for v in n3.weights), ";    ", end="")
            print("w4:", ", ".join(str(v) for v in n4.weights), ";    ")
            count += 1
            for i in range(len(x)):
                y_i = n4.activate([n1.activate(x[i]), n2.activate(x[i]), n3.activate(x[i])])
                print(f"x[{int(x[i][0])},{int(x[i][1])},{int(x[i][2])}] -> [{int(n1.y)},{int(n2.y)},{int(n3.y)}] -> {int(y_i)}")
    print("-------------------------------", count)
    print()
bin_func3_neuron_test()

d: 0, 0, 0, 1, 1, 1, 1, 0;


KeyboardInterrupt: 